_BASE_: "Base-DiffusionDet.yaml" # 继承基础配置
MODEL:
  RESNETS:
    DEPTH: 18            # 使用 ResNet-18，默认 ResNet-50
    STRIDE_IN_1X1: False
    RES2_OUT_CHANNELS: 64 # ResNet-18 的初始通道数，修改此项可减小模型大小，默认直接删
  DiffusionDet:
    NUM_PROPOSALS: 500   # 每一帧生成的随机框数量
    NUM_CLASSES: 1       # 【重要：改为 1 类 (ship)】
    HIDDEN_DIM: 64      # Transformer 中间特征维度，修改此项可减小模型大小，默认直接删
DATASETS:
  TRAIN: ("sar_ship_train",) # 必须与你注册的数据集名称一致
  TEST: ("sar_ship_val",)
SOLVER:
  # 【计算处：根据 Epoch 200 重新计算 MAX_ITER】
  # 假设数据集有 10000 | 31783 张图，BatchSize=32 | 16 ，Epoch=200
  # MAX_ITER = (31783 / 64) * 200 = 99356 约等于 99400
  MAX_ITER: 99400 # 397288
  CHECKPOINT_PERIOD: 5000 # 每 10000 次迭代保存一次模型
  STEPS: (278102,357559)   # 在总迭代的 70% 和 90% 处降学习率
INPUT:
  CROP:
    ENABLED: True         # 开启随机裁剪增强

