"""LPI experiment identity, immutable input checks and prediction interchange (no ML imports)."""
from __future__ import annotations

import hashlib
import json
import math
import os
from pathlib import Path
import subprocess
import sys
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from tools.validate_experiment_configs import resolved_config

DATA = ROOT / 'LPI_COCO'
NAMES = ['LFM', 'NLFM', 'BPSK', 'BFSK', 'Frank']
SEED = 40244023
PYTHONS = {k: Path('/home/troy/anaconda3/envs') / k / 'bin/python' for k in ('Difdet', 'yolo')}
CONFIGS = {**{f'lpi-{i:03d}': ROOT / f'configs/experiments/lpi/lpi-{i:03d}.yaml' for i in (1, 2)},
           **{f'yolo-lpi-{i:03d}': ROOT / f'configs/yolo/lpi/yolo-lpi-{i:03d}.yaml' for i in (1, 2, 3)}}
PROTOCOL = {'version': 1, 'imgsz': 640, 'batch': 1, 'max_det': 100, 'conf': 0.0,
            'seed': SEED, 'matching_iou': 0.5, 'score_comparison': '>=',
            'diffusion_seed': 'sha256(seed:split:image_id) first 32 bits',
            'postprocess': {'diffusiondet': 'native class-aware NMS 0.5; sample_step=1',
                            'yolo11n/yolov8n': 'class-aware NMS 0.7', 'yolo26n': 'native end2end'}}


def sha256(path):
    h = hashlib.sha256()
    with Path(path).open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=False).encode()).hexdigest()


def read_json(path):
    return json.loads(Path(path).read_text(encoding='utf-8'))


def write_json(path, value):
    path = Path(path)
    tmp = path.with_suffix(path.suffix + '.partial')
    tmp.write_text(json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True, allow_nan=False) + '\n', encoding='utf-8')
    tmp.replace(path)


def timestamp():
    return datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S.%fZ')


def git_state():
    def git(*args):
        return subprocess.check_output(['git', *args], cwd=ROOT, text=True).strip()
    return {'commit': git('rev-parse', 'HEAD'), 'status': git('status', '--porcelain')}


def run_python(env, script, *args):
    subprocess.run([str(PYTHONS[env]), str(ROOT / script), *map(str, args)], cwd=ROOT,
                   env={**os.environ, 'PYTHONNOUSERSITE': '1'}, check=True)


def experiment(experiment_id):
    if experiment_id not in CONFIGS:
        raise ValueError(f'未知 LPI 实验：{experiment_id}; 可选 {list(CONFIGS)}')
    path = CONFIGS[experiment_id]
    cfg = resolved_config(path)
    yolo = experiment_id.startswith('yolo-')
    run = ROOT / cfg['project'] / cfg['name'] if yolo else ROOT / cfg['EXPERIMENT']['OUTPUT_ROOT'] / 'lpi' / (experiment_id + '__' + cfg['EXPERIMENT']['NAME'])
    weights = run / ('weights/best.pt' if yolo else 'model_best.pth')
    return path, cfg, run.resolve(), weights


def load_annotations(data_root, split):
    path = Path(data_root) / 'annotations' / f'instances_{split}.json'
    coco = read_json(path)
    if coco['categories'] != [{'id': i + 1, 'name': n} for i, n in enumerate(NAMES)]:
        raise ValueError('COCO 五类映射错误')
    images = {im['id']: im for im in coco['images']}
    if len(images) != len(coco['images']):
        raise ValueError('重复 image_id')
    gt = {i: [] for i in images}
    annotation_ids = set()
    for ann in coco['annotations']:
        if ann['id'] in annotation_ids or ann['image_id'] not in gt or ann['category_id'] not in range(1, 6):
            raise ValueError('标注引用或 ID 错误')
        annotation_ids.add(ann['id'])
        if ann.get('iscrowd', 0):
            raise ValueError('本协议不支持 crowd')
        box = ann['bbox']
        if len(box) != 4 or not all(math.isfinite(v) for v in box) or min(box[2:]) <= 0:
            raise ValueError('无效真实框')
        gt[ann['image_id']].append(ann)
    for i, im in images.items():
        if 'snr_db' not in im or 'scene_id' not in im:
            raise ValueError('缺少 SNR/scene_id')
        if bool(gt[i]) != (im['snr_db'] is not None):
            raise ValueError('纯噪声必须没有 SNR，有信号图片必须有 SNR')
        if im['snr_db'] is not None and not math.isfinite(im['snr_db']):
            raise ValueError('SNR 必须为有限数值')
        if not (Path(data_root) / im['file_name']).resolve().is_relative_to(Path(data_root).resolve()):
            raise ValueError('图片路径越界')
    return coco, images, gt


def check_dataset(data_root=DATA):
    """Check frozen summaries and every label against COCO, without modifying dataset."""
    data_root = Path(data_root)
    manifest = read_json(data_root / 'dataset_manifest.json')
    if manifest['status'] != 'completed' or manifest.get('preview'):
        raise ValueError('正式训练要求 completed 正式数据集')
    # Artifacts are the generator's immutable summaries, not caches generated by YOLO.
    for rel, expected in manifest['artifacts'].items():
        actual = sha256(data_root / rel)
        if actual != expected:
            raise ValueError(f'数据清单哈希不一致：{rel}')
    scenes = set()
    counts = {}
    for split, expected in [('train', (39600, 95040, 3960)), ('val', (9900, 23760, 990)), ('test', (49500, 118800, 4950))]:
        coco, images, gt = load_annotations(data_root, split)
        counts[split] = (len(images), len(coco['annotations']), sum(not x for x in gt.values()))
        if counts[split] != expected:
            raise ValueError(f'{split} 配额错误：{counts[split]}')
        split_scenes = {im['scene_id'] for im in images.values()}
        if split_scenes & scenes:
            raise ValueError('跨子集场景泄漏')
        scenes |= split_scenes
        for i, im in images.items():
            image_path = data_root / im['file_name']
            if not image_path.is_file() or (im['height'], im['width']) != (640, 640):
                raise ValueError(f'图片缺失或尺寸错误：{image_path}')
            label = data_root / 'labels' / split / (image_path.stem + '.txt')
            rows = [list(map(float, line.split())) for line in label.read_text().splitlines() if line.strip()]
            if len(rows) != len(gt[i]):
                raise ValueError(f'YOLO 框数不一致：{label}')
            expected_rows = []
            for a in gt[i]:
                x, y, w, h = a['bbox']
                expected_rows.append([a['category_id'] - 1, (x+w/2)/640, (y+h/2)/640, w/640, h/640])
            for row, ref in zip(sorted(rows), sorted(expected_rows)):
                if len(row) != 5 or any(not math.isfinite(a) or abs(a-b) > 1e-8 for a, b in zip(row, ref)):
                    raise ValueError(f'YOLO/COCO 不一致：{label}')
    return {'manifest_sha256': sha256(data_root / 'dataset_manifest.json'), 'counts': counts}


def inference_implementation(config):
    yolo = 'model' in resolved_config(Path(config))
    env_root = PYTHONS['yolo' if yolo else 'Difdet'].parent.parent
    site = env_root / 'lib/python3.10/site-packages'
    modules = list((ROOT/'diffusiondet').rglob('*.py')) if not yolo else list((site/'ultralytics').rglob('*.py'))
    if not yolo:
        modules += list((ROOT/'detectron2/modeling').rglob('*.py'))
        modules += list((ROOT/'detectron2/data').rglob('*.py'))
    modules += [ROOT/'tools'/name for name in ('lpi_common.py','lpi_predict.py','lpi_train.py','lpi_yolo.py')]
    packages = ['torch','torchvision','numpy','ultralytics' if yolo else 'timm']
    versions = {name: sorted(p.name for p in site.glob(name+'-*.dist-info')) for name in packages}
    return digest({'sources': {str(p):sha256(p) for p in sorted(set(modules))}, 'packages':versions})


def prediction_identity(config, weights, data_root, split):
    return {'config_sha256': digest(resolved_config(Path(config))), 'weights_sha256': sha256(weights),
            'annotations_sha256': sha256(Path(data_root) / 'annotations' / f'instances_{split}.json'),
            'dataset_manifest_sha256': sha256(Path(data_root) / 'dataset_manifest.json'),
            'split': split, 'protocol': PROTOCOL, 'implementation_sha256': inference_implementation(config)}


def load_predictions(bundle, data_root, split, expected_identity=None):
    bundle = Path(bundle)
    manifest = read_json(bundle / 'manifest.json')
    if manifest.get('status') != 'completed' or manifest['identity']['split'] != split:
        raise ValueError('预测未完成或 split 错误')
    if expected_identity is not None and manifest['identity'] != expected_identity:
        raise ValueError('预测指纹与当前权重/配置/协议不一致，拒绝复用')
    _, images, _ = load_annotations(data_root, split)
    if manifest['identity']['annotations_sha256'] != sha256(Path(data_root) / 'annotations' / f'instances_{split}.json') or manifest['identity']['dataset_manifest_sha256'] != sha256(Path(data_root) / 'dataset_manifest.json'):
        raise ValueError('预测与数据指纹不一致')
    if sha256(bundle / 'predictions.jsonl') != manifest['predictions_sha256']:
        raise ValueError('预测文件哈希不一致')
    predictions = {}
    with (bundle / 'predictions.jsonl').open() as f:
        for line in f:
            row = json.loads(line)
            i = row['image_id']
            if i not in images or i in predictions:
                raise ValueError('预测 image_id 未知或重复')
            values = row['detections']
            if not isinstance(values, list) or len(values) > 100:
                raise ValueError('预测必须是最多 100 框的列表')
            for det in values:
                if det['category_id'] not in range(1, 6) or not math.isfinite(det['score']) or not 0 <= det['score'] <= 1:
                    raise ValueError('预测类别或分数非法')
                box = det['bbox']
                if len(box) != 4 or not all(math.isfinite(v) for v in box) or min(box[2:]) < 0:
                    raise ValueError('预测框非法')
            predictions[i] = values
    if set(predictions) != set(images) or manifest['image_count'] != len(images):
        raise ValueError('预测图片覆盖不完整（无预测图片也必须有记录）')
    return predictions, manifest
